# AssayBio Kubernetes命名空间配置
apiVersion: v1
kind: Namespace
metadata:
  name: assaybio-production
  labels:
    name: assaybio-production
    environment: production
    project: assaybio-website
    managed-by: kubernetes
  annotations:
    description: "AssayBio企业网站生产环境命名空间"
    created-by: "DevOps团队"
---
# 资源限制配置
apiVersion: v1
kind: ResourceQuota
metadata:
  name: assaybio-resource-quota
  namespace: assaybio-production
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
# 网络策略配置
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: assaybio-network-policy
  namespace: assaybio-production
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: monitoring
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443