version: '3.8'

services:
  # AssayBio 网站前端服务
  assaybio-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    container_name: assaybio-website
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # SSL证书挂载（生产环境使用）
      - ./ssl:/etc/nginx/ssl:ro
      # 日志持久化
      - ./logs/nginx:/var/log/nginx
      # 自定义配置（如需要）
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NODE_ENV=production
    networks:
      - assaybio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.service=assaybio-web"
      - "description=AssayBio Official Website"

  # Redis缓存（可选 - 如果需要缓存）
  redis:
    image: redis:7-alpine
    container_name: assaybio-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-assaybio123}
    volumes:
      - redis_data:/data
    networks:
      - assaybio-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - cache

  # Nginx代理（用于SSL终止和负载均衡）
  nginx-proxy:
    image: nginx:1.25-alpine
    container_name: assaybio-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/proxy:/var/log/nginx
    depends_on:
      - assaybio-web
    networks:
      - assaybio-network
    profiles:
      - proxy

networks:
  assaybio-network:
    driver: bridge
    name: assaybio-network

volumes:
  redis_data:
    driver: local
    name: assaybio-redis-data