name: Deploy to gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install and Build
      run: |
        if [ -f "package.json" ]; then
          npm ci
          if npm run | grep -q "build"; then
            npm run build
          fi
        fi
        
    - name: Prepare deployment files
      run: |
        # 创建部署目录
        mkdir -p deploy
        
        # 如果有构建输出目录，复制到deploy
        if [ -d "dist" ]; then
          cp -r dist/* deploy/
        fi
        
        # 复制爬虫内容到deploy目录
        if [ -d "web" ]; then
          LATEST_CRAWL=$(find web -name "assaybio*" -type d | head -1)
          if [ -d "$LATEST_CRAWL" ]; then
            echo "复制爬虫内容: $LATEST_CRAWL"
            cp -r "$LATEST_CRAWL"/* deploy/
          fi
        fi
        
        # 如果没有其他内容，复制测试内容
        if [ -d "test_homepage_fixed" ] && [ -z "$(ls -A deploy 2>/dev/null)" ]; then
          echo "复制测试内容"
          cp -r test_homepage_fixed/* deploy/
        fi
        
        # 如果deploy目录为空，创建一个默认页面
        if [ -z "$(ls -A deploy 2>/dev/null)" ]; then
          echo "创建默认页面"
          cat > deploy/index.html << EOF
        <!DOCTYPE html>
        <html>
        <head>
            <title>AssayBio - 上海安净生物技术有限公司</title>
            <meta charset="utf-8">
        </head>
        <body>
            <h1>AssayBio 网站</h1>
            <p>网站正在建设中...</p>
        </body>
        </html>
        EOF
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        publish_branch: gh-pages